---
name: calc
full_name: CALC
type: app
owner_type: project
status: active
stage: live
testable: true
mission: >
  CALC is a tool that enables government contracting personnel to conduct market research on professional service labor categories more quickly and easily.  It helps save the government money by allowing the acquisition community to make more informed decisions when buying professional services.
description: >
  The Contract Awarded Labor Category (CALC) tool helps the federal contracting community make smarter, faster buying decisions by allowing them to search for hourly labor rates across numerous government contracts. The CALC tool is helping contracting officers move from paper-based research to simple, efficient online search.
impact: >
  Saves contracting officers in the federal government hours of work every week and provides them with better data. By having a tool that understands fair and reasonable prices, contracting officers will be better equipped to negotiate with vendors, which will ensure that the government is spending taxpayer dollars wisely and in the most efficient way.
milestones:
- 'November 2014: The initial discovery stage for CALC begins.'
- 'November 2014: We begin building an alpha version of the site, known as Hourglass.'
- 'March 2015: The name of the site changes from "Hourglass" to "CALC," which stands for "Contract Awarded Labor Category" tool.'
- 'May 2015: We launched the public beta.'
- 'June 2016: Work begins on the second phase of CALC, with the goal of adding price list data capture capabilities.'
contact:
- url: mailto:alan.brouilette@gsa.gov
  text: Alan Broulette
- url: mailto:nicholas.brethauer@gsa.gov
  text: Nicholas Brethauer
stack:
- Python
- Django
- JavaScript
- Postgres

# Services used to supply project status information
# Items:
# - name: Name of the service
#   category: Type of the service
#   url: URL for detailed information
#   badge: URL for the status badge
services:
- name: Travis CI
  category: CI
  url: https://travis-ci.org/18F/calc
  badge: https://travis-ci.org/18F/calc.svg
- name: CodeClimate
  category: Code Review
  url: https://codeclimate.com/github/18F/calc
  badge: https://codeclimate.com/github/18F/calc/badges/gpa.svg
- name: QuantifiedCode
  category: Code Review
  url: https://www.quantifiedcode.com/app/project/2b5fdf07f0434ff7b9d0039905e55793?branch=origin%2Fdevelop
  badge: https://www.quantifiedcode.com/api/v1/project/2b5fdf07f0434ff7b9d0039905e55793/snapshot/origin:develop:HEAD/badge.svg


licenses:
  mirage:
    name: Public Domain (CC0)
    url: https://creativecommons.org/publicdomain/zero/1.0/
links:
- url: https://calc.gsa.gov/
  text: CALC production instance
- url: https:/calc-dev.apps.cloud.gov/
  text: CALC development instance
- url: https://trello.com/b/LjXJaVbZ/hourglass
  text: Original project sprint board
- url: https://trello.com/b/qiJYky5c/calc-data-capture
  text: Data Capture project sprint board

blogTag:
- procurement
- federal acquisitions

partners:
- General Services Administration
team:
- github: toolness
- github: jseppi
- github: hbillings
- github: tram
- github: abrouilette
- github: shawnbot
  role: alum
- github: maya
  role: alum
- github: brethauer
  role: alum
- github: xtine
  role: alum
- github: kaitlin
  role: alum
- github: arowla
  role: alum
- github: jmcarp
  role: alum
- github: theresaanna
  role: alum
tasks: https://github.com/18F/calc/issues
github:
- 18F/calc
