languages:
  JavaScript: true
  Python: true
exclude_paths:
- "hourglass_site/static/hourglass_site/js/vendor/*"
- "contracts/migrations/*"
- "hourglass_site/static/hourglass_site/tests/*"
- "selenium_tests/*"

