language: python
python:
- 3.4
addons:
  postgresql: 9.3
matrix:
  fast_finish: true
before_install:
- pip install codeclimate-test-reporter
after_success:
- codeclimate-test-reporter
install:
- pip install -r requirements.txt
script:
- phantomjs --version
- echo "For details on why we're ignoring selenium tests, see https://github.com/18F/calc/issues/330"
- py.test --ignore=selenium_tests --cov
env:
  global:
  - PHANTOMJS_TIMEOUT=15
  - DEBUG=yup
  - DATABASE_URL=postgres://postgres@localhost/hourglass
notifications:
  email: false
deploy:
  edge: true
  provider: cloudfoundry
  username: deploy-hourglass
  password:
    secure: "YR1jjKUf+J0yqPpuGX4J198ZC7ibhzVEV1D+cYcX9Ti2gpBl08uo60G0stOzovH9M8E21Tv5/qkgrGy0HE4/Qc7hK8Lw68Ia6D5T8Tkt/rTlnMp2eRThRN3HXWLS0gblRiHViwUOEjpbcrJ9nH8bbAgeZlL84HMipguPsnLuv6c="
  api: https://api.cloud.gov
  organization: oasis
  space: calc-dev
  on:
    branch: develop
sudo: required
