language: python
python:
- 3.4
addons:
  postgresql: 9.3
matrix:
  fast_finish: true
before_install:
- pip install codeclimate-test-reporter
after_success:
- codeclimate-test-reporter
install:
- pip install -r requirements.txt
script:
- phantomjs --version
- echo "For details on why we're ignoring selenium tests, see https://github.com/18F/calc/issues/330"
- py.test --ignore=selenium_tests --cov
env:
  global:
  - PHANTOMJS_TIMEOUT=15
  - DEBUG=yup
  - DATABASE_URL=postgres://postgres@localhost/hourglass
notifications:
  email: false
deploy:
  edge: true
  provider: cloudfoundry
  username: deploy-hourglass
  password:
    secure: "dHsbCYyIb6GVhXioJvKaiNNcPfZuHcOKH8Ojci6EANC4gkxh3Xgtxg/fL/0I5twNM1NQFB7ERlzcsF/8f3FbhdXPYqRoTtgY4ej2t/v6POHHbNaaE9zDWe6z0jtGUWgnrwlsmv0urFigYxTBLgydtmps988/iEgNf+L0C2SjnvQ="
  api: https://api.cloud.gov
  organization: oasis
  space: calc-dev
  manifest: manifests/manifest-staging.yml
  on:
    branch: develop
sudo: required
