---
services:
- db-calc-dev
- calc-env
applications:
- name: calc-dev
  instances: 1
  memory: 256M
  disk_quota: 1024M
  host: calc-dev
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
