---
services:
- db-calc-sandbox
- calc-env
applications:
- name: calc-sandbox
  instances: 1
  memory: 256M
  disk_quota: 1024M
  host: calc-sandbox
  domain: apps.cloud.gov
  buildpack: python_buildpack
  command: bash cf.sh
  stack: cflinuxfs2
  timeout: 180
